services:
  mysql:
    container_name: mysql-container
    # Remove the build stage if you want to pull the existing container.
    build:
      context: .
      dockerfile: mysql.Dockerfile
    image: cat-i-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cms
      MYSQL_USER: cms
      MYSQL_PASSWORD: cms
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      test: mysqladmin ping -h 127.0.0.1 -u cms --password=cms
      interval: 10s
      timeout: 5s
      retries: 5
    # volumes:
    #   - ./DataModel/InitializationScripts:/docker-entrypoint-initdb.d
    command: --lower_case_table_names=1
  app:
    container_name: cat-i-container
    # Remove the build stage if you want to pull the existing container.
    build:
      context: .
      dockerfile: CMS/Dockerfile
    image: cat-i-app
    ports:
      # - "80:80"
      - "443:443"
      # - "44389:44389"
      # - "5353:5353"
    networks:
      - mynetwork
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__DefaultConnection=Server=mysql;database=cmsusers;user=cms;password=cms;pooling=true; # Set your database password here
      - ConnectionStrings__CMSConnection=Server=mysql;database=cms;user=cms;password=cms;pooling=true; # And here
      - ASPNETCORE_Kestrel__Certificates__Default__Password=certificate_password  # Set your certificate password here
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
        - ~/.aspnet/https:/https:ro
    depends_on:
        mysql:
            condition: service_healthy
            restart: true
networks:
  mynetwork:
    driver: bridge